---
- name: Configure all nodes
  hosts: all
  become: true
  roles:
    - common

- name: Build web tier
  hosts: webservers
  become: true
  roles:
    - webserver

- name: Build load balancer
  hosts: loadbalancer
  become: true
  roles:
    - loadbalancer
