---
- name: UFW reset to defaults
  community.general.ufw:
    state: reset
    direction: incoming

# THIS NEEDS TO BE DONE FIRST
- name: UFW public ssh for loadbalancer
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop:
    - 22
    - 80
    - "60000:65000"
  when: "'loadbalancer' in group_names"

- name: UFW ssh access from loadbalancer to internal hosts
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
    from_ip: "{{ hostvars['loadbalancer'].ansible_host }}"
  loop:
    - 22
    - 80
  when: "'internal' in group_names"

- name: UFW default-deny and enable
  community.general.ufw:
    state: enabled
    default: deny

- name: Harden SSH
  ansible.builtin.template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: "0600"
  notify: Restart ssh
